college/urls.py
from django.urls import path
from.views import*

app_name = 'college'

urlpatterns=[
    path('details/',college_add.as_view(),name="details"),
    path('college_notification/', CollegeNotification.as_view(), name='college_notification'),
    path('notification_view/',notification_views.as_view(),name="notification_view"),
    path('EDIT/<int:id>',notification_edit.as_view(),name="EDIT"),
    path('Deleting/<int:id>',notification_delete.as_view(),name="Deleting"),
    path('add_addmission/',addmission_add.as_view(),name="add_addmission"),
    path('view_addmission/',addmission_view.as_view(),name="view_addmission"),
    path('edit_addmission/<int:id>',addmission_edit.as_view(),name="edit_addmission"),
    path('delete_addmission/<int:id>',addmission_delete.as_view(),name="delete_addmission"),
    path('add_document/',document_add.as_view(),name="add_document"),
    path('document_view/',document_view.as_view(),name="document_view"),
    path('document_edit/<int:id>',document_edit.as_view(),name="document_edit"),
    path('document_delte/<int:id>',document_delete.as_view(),name="document_delte"),
    path('facility_add/',college_facilites.as_view(),name="facility_add"),
    path('view_facility/',facility_view.as_view(),name="view_facility"),
    path('edit_facility/<int:id>',facility_editing.as_view(),name="edit_facility"),
    path('facility_delt/<int:id>',facility_delt.as_view(),name="facility_delt"),
    path('add_programme/',programme_add.as_view(),name="add_programme"),
    path('view_programme/',programme_view.as_view(),name="view_programme"),
    path('edit_progarme/<int:id>',programme_edit.as_view(),name="edit_progarme"),
    path('delt_progrm/<int:id>',programm_delt.as_view(),name="delt_progrm"),
    path('national_college/',national_college.as_view(),name="national_college"),
    path('abouts/',about_add.as_view(),name="abouts"),
    path('view_student/',view_std.as_view(),name="view_student"),
    path('Home_view/',home.as_view(),name="Home_view"),
    path('home_add/',add.as_view(),name="home_add"),
    path('home_edit/<int:id>',home_edit.as_view(),name="home_edit"),
    path('home_delt/<int:id>',home_delt.as_view(),name="home_delt"),
    path('collegehome/',college_home.as_view(),name="collegehome"),
    path('vacancy_course/',view_coure.as_view(),name="vacancy_course"),
    path('add_vacancy/',add_vacancy.as_view(),name="add_vacancy"),
    path('edit_vacancyes/<int:id>',vacancy_edit.as_view(),name="edit_vacancyes"),
    path('delt_vacany/<int:id>',VacancyDeleteView.as_view(),name="delt_vacany"),

]

student/urls.py
from django.urls import path
from.views import*

app_name = 'student'

urlpatterns=[
    path('students/',student_add.as_view(),name="students"),
    path('vacancy_college/',college_vacancy.as_view(),name="vacancy_college"),
    path('vacancy_view/',vacancy_view.as_view(),name="vacancy_view"),
    path('view<int:id>/',natonal.as_view(),name="view"),
    path('maharaj/',maharajas.as_view(),name="maharaj"),
    path('request_sends/',request_send.as_view(),name="request_sends"),
    path('add-feedback/', AddFeedback.as_view(), name='add-feedback'),
    path('feedbacks_view/',view_feedback.as_view(),name="feedbacks_view"),
    path('feedback_edit/<int:id>',edit_feedback.as_view(),name="feedback_edit"),
    path('feedback_delt/<int:id>',feedback_delt.as_view(),name="feedback_delt"),
    path('view_college/<int:id>',details_view.as_view(),name="view_college"),
    path('send-request',SendRequestView.as_view(), name='send_request'),
    path('view-requests', view_request.as_view(), name='view_requests'),
    path('send_complt/',SubmitComplaintView.as_view(),name="send_complt"),
    path('viewcolleges/<int:id>/', ViewColleges.as_view(), name='viewcollege'),
    path('aboutss/<int:id>',about_view.as_view(),name="aboutss"),
    path('notifications/<int:id>/', NotificationView.as_view(), name='exmnotification'),
    path('progrmms/<int:id>',ProgrammeView.as_view(), name='progrmmnotification'),
    path('facility_view/<int:id>',Facilitys.as_view(),name="facility"),
    path('addmission/<int:id>',Addmissions.as_view(),name="addmission"),
    path('review/',Submitreview.as_view(),name="review"),
    path('ripl/<int:id>',riplyed.as_view(),name="ripl")

]

university/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('college/',include('college.urls')),
    path('manager/',include('manager.urls')),
    path('',include('userapp.urls',namespace='userapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college/models.py
from django.db import models
from django.template.defaultfilters import default
from userapp.models import *
# Create your models here.

class collegemodel(models.Model):
    user_pages = models.OneToOneField(Usermodel, on_delete=models.CASCADE,null=True,blank=True)
    college_image=models.ImageField(null=True,blank=True,upload_to="images")
    college_name=models.CharField(max_length=30,null=True,blank=True)
    College_code=models.IntegerField(null=True,blank=True)
    Email=models.EmailField(max_length=20,null=True,blank=True)
    Contact_number=models.IntegerField(null=True,blank=True)
    Address=models.CharField(max_length=25,null=True,blank=True)
    City=models.CharField(max_length=20,null=True,blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

class ExamNotification(models.Model):
    subject = models.CharField(max_length=100, null=True, blank=True)
    connect=models.ForeignKey(Usermodel,on_delete=models.CASCADE,null=True,blank=True)
    lock=models.ForeignKey(collegemodel,on_delete=models.CASCADE, null=True, blank=True)
    notification_content = models.TextField(null=True, blank=True)
    exam_date = models.DateTimeField(null=True, blank=True)
    notification_sent = models.DateTimeField(null=True, blank=True)
    status = models.CharField(default="active", max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)




class Addmission_details(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    college_name = models.CharField(max_length=30, null=True, blank=True)
    Eligibility=models.CharField(max_length=30,null=True,blank=True)
    Subject=models.CharField(max_length=20,null=True,blank=True)
    Addmission_start_date = models.DateField(null=True, blank=True)
    Addmission_end_date = models.DateField(null=True, blank=True)


class addmission_documents(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Sslc_certificate=models.FileField(null=True,blank=True,upload_to="Files/")
    Plustwo_certificate=models.FileField(null=True,blank=True,upload_to="Files/")
    ID_card=models.FileField(null=True,blank=True,upload_to="Files/")
    TC=models.FileField(null=True,blank=True,upload_to="Files/")
    CC=models.FileField(null=True,blank=True,upload_to="Files/")


class Facility(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Name=models.CharField(max_length=20,null=True,blank=True)
    Description=models.CharField(max_length=40,null=True,blank=True)
    image=models.ImageField(null=True,blank=True,upload_to="facility/")


class programm_notification(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Titel=models.CharField(max_length=25,null=True,blank=True)
    Venue=models.CharField(max_length=25,null=True,blank=True)
    Start_date=models.DateTimeField(null=True,blank=True)
    End_date=models.DateTimeField(null=True,blank=True)



class vacancy(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Programme = models.CharField(max_length=30,null=True,blank=True)
    Totel_Seat = models.IntegerField(null=True,blank=True)
    Availbale_Seat =models.IntegerField(null=True,blank=True)
    Dead_line=models.DateField(null=True,blank=True)


class about(models.Model):
    title = models.CharField(max_length=140,null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    teammember1=models.CharField(max_length=120,null=True,blank=True)
    teammember2= models.CharField(max_length=120,null=True,blank=True)
    teamimg1 = models.ImageField(upload_to='team_images/', null=True, blank=True)
    teamimg2 = models.ImageField(upload_to='team_images/', null=True, blank=True)
    teamimg3 = models.ImageField(upload_to='team_images/', null=True, blank=True)
    camimg1=models.ImageField(upload_to='images/', null=True, blank=True)
    camimg2 = models.ImageField(upload_to='images/', null=True, blank=True)
    camimg3 = models.ImageField(upload_to='images/', null=True, blank=True)
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)

student/models.py
from django.db import models
from userapp.models import Usermodel
from django.contrib.auth.models import User
from datetime import datetime
from college.models import *


class studentmodel(models.Model):
    Gender_choices = [
        ('MALE', 'male'),
        ('FEMALE', 'female'),
        ('OTHER', 'other')
    ]

    university_under = [
        ('CENTER', 'center'),
        ('CALICUT', 'calicut'),
        ('COCHIN', 'cochin'),
        ('NATIONAL', 'national')
    ]

    Name = models.CharField(max_length=25, null=True, blank=True)
    Age = models.IntegerField(null=True, blank=True)
    Date_of_birth = models.DateField(null=True, blank=True)
    Email = models.EmailField(null=True, blank=True)
    Father_name = models.CharField(max_length=20, null=True, blank=True)
    login_page = models.OneToOneField(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    Mother_name = models.CharField(max_length=20, null=True, blank=True)
    Gender = models.CharField(max_length=10, choices=Gender_choices)
    City = models.CharField(max_length=20, null=True, blank=True)
    Ph_num = models.IntegerField(null=True, blank=True)
    Addar_num = models.IntegerField(null=True, blank=True)
    Qualification = models.CharField(max_length=20, null=True, blank=True)
    University = models.CharField(max_length=20, null=True, blank=True, choices=university_under)
    status = models.CharField(default="active", max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)



class Feedback(models.Model):
    desciption=models.CharField(max_length=30,null=True,blank=True)
    titel=models.CharField(max_length=30,null=True,blank=True)
    status = models.CharField(default="active", max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)




class SeatTransferRequest(models.Model):
    REQUEST_TYPE_CHOICES = [
        ('SEAT', 'Seat Request'),
        ('TRANSFER', 'Transfer Request'),
    ]

    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    ]

    student = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True,blank=True)
    college = models.ForeignKey(collegemodel, on_delete=models.CASCADE)
    program = models.ForeignKey(vacancy, on_delete=models.CASCADE)
    request_type = models.CharField(max_length=10, choices=REQUEST_TYPE_CHOICES)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='PENDING')
    date_submitted = models.DateTimeField(default=datetime.now)
    reason = models.TextField(blank=True, null=True)



class College(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    description = models.TextField()


class review(models.Model):
    user = models.ForeignKey(Usermodel, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(default=0)
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"Feedback from {self.user.username}"

class Complaint(models.Model):
    sender = models.ForeignKey(Usermodel, on_delete=models.CASCADE, blank=True, null=True)
    complaint_text = models.TextField(max_length=1000, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    reply = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=[
            ('pending', 'Pending'),
            ('resolved', 'Resolved'),
            ('under_review', 'Under Review'),
            ('closed', 'Closed'),
        ], default='pending')

    def _str_(self):
        return f"{self.sender.username}"

college/forms.py
from django import forms
from .models import *

class collegeform(forms.ModelForm):
    class Meta:
        model=collegemodel
        fields ='__all__'


class NotificationForm(forms.ModelForm):
    class Meta:
        model = ExamNotification
        fields = ['subject', 'notification_content', 'exam_date']


class addmission_form(forms.ModelForm):
    class Meta:
        model = Addmission_details
        fields = '__all__'

class document_form(forms.ModelForm):
    class Meta:
        model = addmission_documents
        fields = '__all__'

class facility_form(forms.ModelForm):
    class Meta:
        model=Facility
        fields = '__all__'

class programme_form(forms.ModelForm):
    class Meta:
        model=programm_notification
        fields = '__all__'

class vacancy_form(forms.ModelForm):
    class Meta:
        model =vacancy
        fields = '__all__'

class about_form(forms.ModelForm):
    class Meta:
        model = about
        fields = '__all__'
        

student/forms.py
from django import forms
from .models import *

class studentform(forms.ModelForm):
    class Meta:
        model = studentmodel
        fields = [
            'Name', 'Age', 'Date_of_birth', 'Email', 'Father_name', 'Mother_name',
            'Gender', 'City', 'Ph_num', 'Addar_num', 'Qualification'
        ]


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'


class SeatTransferRequestForm(forms.ModelForm):
    class Meta:
        model = SeatTransferRequest
        fields = ['college', 'program', 'request_type', 'reason']


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['complaint_text']
        widgets = {
            'complaint_text': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }

templates/student/college_details.html
<!DOCTYPE html>
<html>
<head>
    <title></title>

</head>
<body>
<div>
    <img src="{{ details.home_image.url }}" class="card-img-top" alt="College Image" >
    <h5 class="card-title">{{ details.titel }}</h5>
    <p class="card-text">{{ details.Location }}</p>
    <a href="{{ details.id }}" class="btn btn-primary">View</a>
</div>
</body>
</html>

templates/student/college_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>College Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <style>

        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }
        .navbar {
            height: 80px;
            font-size: 18px;
            font-weight: 600;
            background: linear-gradient(to right, #007bff, #0056b3);
        }
        .navbar-brand h2 {
            color: #fff;
            margin: 0;
            font-style: italic;
            font-weight: 700;
            
        }
        .navbar-nav .nav-link {
            color: #ffffff;
            padding-right:60px;
            font-style: italic;
            transition: color 0.3s;
            font-size: 21px;
        }
        li{
          padding-right: 70px;
        }
        .navbar-nav .nav-link:hover {
            color: #ffdd57;
        }
        .dropdown-menu li a:hover {
            background-color: #007bff;
            color: #ffffff;
        }
        .carousel-inner img {
            width: 100%;
            height: 600px;
            object-fit: cover;
        }
        .container {
            padding: 40px 15px;
        }
        h1 {
            font-size: 36px;
            color: #343a40;
            margin-bottom: 20px;
            text-align: center;
        }
        .college-details p {
            font-size: 18px;
            line-height: 1.8;
        }
        .college-details p strong {
            color: #0056b3;
        }
        footer {
            margin-top: 40px;
            background: #343a40;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }
        footer p {
            margin: 0;
        }
    </style>
</head>
<body>


<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><h2>{{ det.college_name }}</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student:aboutss' det.id %}">About </a>
        </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'student:review' %}">Reviews</a>
           </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student:facility' det.id %}">Facility</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'student:addmission' det.id %}">Admission</a>
        </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'student:send_complt' %}">Complaints</a>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Request
          </a>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'student:send_request'  %}">Send request</a></li>
              <li><a class="dropdown-item" href="{% url 'student:view_requests'  %}">View Status</a></li>
</ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Notifications
          </a>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'student:exmnotification' det.id %}">Exam Notifications</a></li>
              <li><a class="dropdown-item" href="{% url 'student:progrmmnotification' det.id %}">programme notificatin</a></li>
</ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ det.college_image.url }}" alt="College Image">
    </div>
  </div>
</div>

<div class="container">
    <h1>College Details</h1>
    <div class="college-details">

        <p><strong>College Code:</strong> {{ det.College_code }}</p>
        <p><strong>Email:</strong> {{ det.Email }}</p>
        <p><strong>Contact Number:</strong> {{ det.Contact_number }}</p>
        <p><strong>City:</strong> {{ det.City }}</p>
    </div>
</div>

</body>
</html>


















<footer>
    <p>&copy; 2025 Harvard University. All Rights Reserved.</p>
</footer>

{% block body %}
{% endblock %}
</body>
</html>

templates/student/feedback_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for feedback in view %}
<table border="1px solid black">
    <tr>
<th>
      <label>Titel</label></th>
       <td>{{feedback.titel }}</td>
    </tr>
    <tr>
        <th><lable>Message </lable></th>
        <td>{{ feedback.desciption }}</td>
    </tr>
</table>

<button> <a href="{% url 'student:feedback_edit' feedback.id %}">Edit</a></button>
<button> <a href="{% url 'student:feedback_delt' feedback.id %}">Delete</a></button>
{% endfor %}
</body>
</html>

templates/student/send_request.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Send Seat or Transfer Request</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        h2 {
            text-align: center;
            color: #333;
            margin-top: 20px;
        }
        form {
            width: 60%;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        label {
            display: block;
            margin: 10px 0 5px;
            font-weight: bold;
        }
        input, select, textarea, button {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        button {
            background-color: #007bff;
            color: white;
            border: none;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
<h2>Send Seat or Transfer Request</h2>
<form method="post">
    {% csrf_token %}

    <label for="student_name">Student Name</label>
    <input type="text" id="student_name" name="student_name" placeholder="Enter student name" required>

    <label for="program">Program</label>
   <input type="text" id="id_program" name="program" placeholder="programme">

    <label for="request_type">Request Type</label>
    <select id="request_type" name="request_type" required>
        <option value="">Select request type</option>
        <option value="seat">Seat Request</option>
        <option value="transfer">Transfer Request</option>
    </select>

    <label for="reason">Reason for Request</label>
    <textarea id="reason" name="reason" rows="4" placeholder="Enter your reason here" required></textarea>

    <button type="submit">Submit Request</button>
</form>

<h3>Available Vacancies</h3>
<ul>
    {% for vacancy in vacancy %}
        <li>{{ vacancy.name }}</li>
    {% empty %}
        <li>No vacancies available.</li>
    {% endfor %}
</ul>
</body>
</html>

templates/student/vacancy_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
<h1 class="text-center my-4">Colleges</h1>

<div class="container-fluid">
    <div class="row justify-content-center">
        {% for details in data %}
        <div class="col-12 col-md-6 col-lg-4 mb-4">
            <div class="card h-100">
                {% if details.college_image %}
                <img src="{{ details.college_image.url }}" class="card-img-top" alt="College Image" style="object-fit: cover; width: 100%; height: 200px;">
                {% else %}
                <div class="d-flex align-items-center justify-content-center" style="height: 200px; background-color: #f8f9fa;">
                    <p class="text-center text-muted mb-0">No image available</p>
                </div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ details.college_name }}</h5>
                    <p class="card-text">{{ details.City|default:"Location not specified" }}</p>
                    <a href="{% url 'student:viewcollege' details.id %}" class="btn btn-primary">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</body>
</html>

templates/student/view_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    margin: 0;
    padding: 0;
}

h2 {
    text-align: center;
    color: #333;
    margin-top: 20px;
}

table {
    width: 80%;
    margin: 20px auto;
    border-collapse: collapse;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    background-color: #fff;
}

th, td {
    padding: 12px 15px;
    text-align: left;
}

th {
    background-color: #007bff;
    color: #fff;
    text-transform: uppercase;
}

td {
    border-bottom: 1px solid #ddd;
}

tr:nth-child(even) {
    background-color: #f9f9f9;
}

tr:hover {
    background-color: #f1f1f1;
    cursor: pointer;
}

th:first-child, td:first-child {
    border-left: 1px solid #ddd;
}

th:last-child, td:last-child {
    border-right: 1px solid #ddd;
}

@media screen and (max-width: 768px) {
    table {
        width: 100%;
    }

    th, td {
        padding: 8px;
        font-size: 14px;
    }

    h2 {
        font-size: 20px;
    }
}

    </style>
</head>
<body>
<h2>Your Requests</h2>
<table>
    <tr>
        <th>College</th>
        <th>Program</th>
        <th>Request Type</th>
        <th>Status</th>
        <th>Date Submitted</th>
    </tr>
    {% for request in requests %}
    <tr>
        <td>{{ request.college.name }}</td>
        <td>{{ request.program.name }}</td>
        <td>{{ request.get_request_type_display }}</td>
        <td>{{ request.get_status_display }}</td>
        <td>{{ request.date_submitted }}</td>
    </tr>
    {% endfor %}
</table>

</body>
</html>