college/urls.py
from django.urls import path
from.views import*

app_name = 'college'

urlpatterns=[
    path('details/',college_add.as_view(),name="details"),
    path('college_notification/', CollegeNotification.as_view(), name='college_notification'),
    path('notification_view/',notification_views.as_view(),name="notification_view"),
    path('EDIT/<int:id>',notification_edit.as_view(),name="EDIT"),
    path('Deleting/<int:id>',notification_delete.as_view(),name="Deleting"),
    path('add_addmission/',addmission_add.as_view(),name="add_addmission"),
    path('view_addmission/',addmission_view.as_view(),name="view_addmission"),
    path('edit_addmission/<int:id>',addmission_edit.as_view(),name="edit_addmission"),
    path('delete_addmission/<int:id>',addmission_delete.as_view(),name="delete_addmission"),
    path('add_document/',document_add.as_view(),name="add_document"),
    path('document_view/',document_view.as_view(),name="document_view"),
    path('document_edit/<int:id>',document_edit.as_view(),name="document_edit"),
    path('document_delte/<int:id>',document_delete.as_view(),name="document_delte"),
    path('facility_add/',college_facilites.as_view(),name="facility_add"),
    path('view_facility/',facility_view.as_view(),name="view_facility"),
    path('edit_facility/<int:id>',facility_editing.as_view(),name="edit_facility"),
    path('facility_delt/<int:id>',facility_delt.as_view(),name="facility_delt"),
    path('add_programme/',programme_add.as_view(),name="add_programme"),
    path('view_programme/',programme_view.as_view(),name="view_programme"),
    path('edit_progarme/<int:id>',programme_edit.as_view(),name="edit_progarme"),
    path('delt_progrm/<int:id>',programm_delt.as_view(),name="delt_progrm"),
    path('national_college/',national_college.as_view(),name="national_college"),
    path('abouts/',about_add.as_view(),name="abouts"),
    path('view_student/',view_std.as_view(),name="view_student"),
    path('Home_view/',home.as_view(),name="Home_view"),
    path('home_add/',add.as_view(),name="home_add"),
    path('home_edit/<int:id>',home_edit.as_view(),name="home_edit"),
    path('home_delt/<int:id>',home_delt.as_view(),name="home_delt"),
    path('collegehome/',college_home.as_view(),name="collegehome"),
    path('vacancy_course/',view_coure.as_view(),name="vacancy_course"),
    path('add_vacancy/',add_vacancy.as_view(),name="add_vacancy"),
    path('edit_vacancyes/<int:id>',vacancy_edit.as_view(),name="edit_vacancyes"),
    path('delt_vacany/<int:id>',VacancyDeleteView.as_view(),name="delt_vacany"),

]

student/urls.py
from django.urls import path
from.views import*

app_name = 'student'

urlpatterns=[
    path('students/',student_add.as_view(),name="students"),
    path('vacancy_college/',college_vacancy.as_view(),name="vacancy_college"),
    path('vacancy_view/',vacancy_view.as_view(),name="vacancy_view"),
    path('view<int:id>/',natonal.as_view(),name="view"),
    path('maharaj/',maharajas.as_view(),name="maharaj"),
    path('request_sends/',request_send.as_view(),name="request_sends"),
    path('add-feedback/', AddFeedback.as_view(), name='add-feedback'),
    path('feedbacks_view/',view_feedback.as_view(),name="feedbacks_view"),
    path('feedback_edit/<int:id>',edit_feedback.as_view(),name="feedback_edit"),
    path('feedback_delt/<int:id>',feedback_delt.as_view(),name="feedback_delt"),
    path('view_college/<int:id>',details_view.as_view(),name="view_college"),
    path('send-request',SendRequestView.as_view(), name='send_request'),
    path('view-requests', view_request.as_view(), name='view_requests'),
    path('send_complt/',SubmitComplaintView.as_view(),name="send_complt"),
    path('viewcolleges/<int:id>/', ViewColleges.as_view(), name='viewcollege'),
    path('aboutss/<int:id>',about_view.as_view(),name="aboutss"),
    path('notifications/<int:id>/', NotificationView.as_view(), name='exmnotification'),
    path('progrmms/<int:id>',ProgrammeView.as_view(), name='progrmmnotification'),
    path('facility_view/<int:id>',Facilitys.as_view(),name="facility"),
    path('addmission/<int:id>',Addmissions.as_view(),name="addmission"),
    path('review/',Submitreview.as_view(),name="review"),
    path('ripl/<int:id>',riplyed.as_view(),name="ripl")

]

university/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('college/',include('college.urls')),
    path('manager/',include('manager.urls')),
    path('',include('userapp.urls',namespace='userapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college/models.py
from django.db import models
from django.template.defaultfilters import default
from userapp.models import *
# Create your models here.

class collegemodel(models.Model):
    user_pages = models.OneToOneField(Usermodel, on_delete=models.CASCADE,null=True,blank=True)
    college_image=models.ImageField(null=True,blank=True,upload_to="images")
    college_name=models.CharField(max_length=30,null=True,blank=True)
    College_code=models.IntegerField(null=True,blank=True)
    Email=models.EmailField(max_length=20,null=True,blank=True)
    Contact_number=models.IntegerField(null=True,blank=True)
    Address=models.CharField(max_length=25,null=True,blank=True)
    City=models.CharField(max_length=20,null=True,blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

class ExamNotification(models.Model):
    subject = models.CharField(max_length=100, null=True, blank=True)
    connect=models.ForeignKey(Usermodel,on_delete=models.CASCADE,null=True,blank=True)
    lock=models.ForeignKey(collegemodel,on_delete=models.CASCADE, null=True, blank=True)
    notification_content = models.TextField(null=True, blank=True)
    exam_date = models.DateTimeField(null=True, blank=True)
    notification_sent = models.DateTimeField(null=True, blank=True)
    status = models.CharField(default="active", max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)




class Addmission_details(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    college_name = models.CharField(max_length=30, null=True, blank=True)
    Eligibility=models.CharField(max_length=30,null=True,blank=True)
    Subject=models.CharField(max_length=20,null=True,blank=True)
    Addmission_start_date = models.DateField(null=True, blank=True)
    Addmission_end_date = models.DateField(null=True, blank=True)


class addmission_documents(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Sslc_certificate=models.FileField(null=True,blank=True,upload_to="Files/")
    Plustwo_certificate=models.FileField(null=True,blank=True,upload_to="Files/")
    ID_card=models.FileField(null=True,blank=True,upload_to="Files/")
    TC=models.FileField(null=True,blank=True,upload_to="Files/")
    CC=models.FileField(null=True,blank=True,upload_to="Files/")


class Facility(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Name=models.CharField(max_length=20,null=True,blank=True)
    Description=models.CharField(max_length=40,null=True,blank=True)
    image=models.ImageField(null=True,blank=True,upload_to="facility/")


class programm_notification(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Titel=models.CharField(max_length=25,null=True,blank=True)
    Venue=models.CharField(max_length=25,null=True,blank=True)
    Start_date=models.DateTimeField(null=True,blank=True)
    End_date=models.DateTimeField(null=True,blank=True)



class vacancy(models.Model):
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)
    Programme = models.CharField(max_length=30,null=True,blank=True)
    Totel_Seat = models.IntegerField(null=True,blank=True)
    Availbale_Seat =models.IntegerField(null=True,blank=True)
    Dead_line=models.DateField(null=True,blank=True)


class about(models.Model):
    title = models.CharField(max_length=140,null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    teammember1=models.CharField(max_length=120,null=True,blank=True)
    teammember2= models.CharField(max_length=120,null=True,blank=True)
    teamimg1 = models.ImageField(upload_to='team_images/', null=True, blank=True)
    teamimg2 = models.ImageField(upload_to='team_images/', null=True, blank=True)
    teamimg3 = models.ImageField(upload_to='team_images/', null=True, blank=True)
    camimg1=models.ImageField(upload_to='images/', null=True, blank=True)
    camimg2 = models.ImageField(upload_to='images/', null=True, blank=True)
    camimg3 = models.ImageField(upload_to='images/', null=True, blank=True)
    connect = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    lock = models.ForeignKey(collegemodel, on_delete=models.CASCADE, null=True, blank=True)

student/models.py
from django.db import models
from userapp.models import Usermodel
from django.contrib.auth.models import User
from datetime import datetime
from college.models import *


class studentmodel(models.Model):
    Gender_choices = [
        ('MALE', 'male'),
        ('FEMALE', 'female'),
        ('OTHER', 'other')
    ]

    university_under = [
        ('CENTER', 'center'),
        ('CALICUT', 'calicut'),
        ('COCHIN', 'cochin'),
        ('NATIONAL', 'national')
    ]

    Name = models.CharField(max_length=25, null=True, blank=True)
    Age = models.IntegerField(null=True, blank=True)
    Date_of_birth = models.DateField(null=True, blank=True)
    Email = models.EmailField(null=True, blank=True)
    Father_name = models.CharField(max_length=20, null=True, blank=True)
    login_page = models.OneToOneField(Usermodel, on_delete=models.CASCADE, null=True, blank=True)
    Mother_name = models.CharField(max_length=20, null=True, blank=True)
    Gender = models.CharField(max_length=10, choices=Gender_choices)
    City = models.CharField(max_length=20, null=True, blank=True)
    Ph_num = models.IntegerField(null=True, blank=True)
    Addar_num = models.IntegerField(null=True, blank=True)
    Qualification = models.CharField(max_length=20, null=True, blank=True)
    University = models.CharField(max_length=20, null=True, blank=True, choices=university_under)
    status = models.CharField(default="active", max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)



class Feedback(models.Model):
    desciption=models.CharField(max_length=30,null=True,blank=True)
    titel=models.CharField(max_length=30,null=True,blank=True)
    status = models.CharField(default="active", max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)




class SeatTransferRequest(models.Model):
    REQUEST_TYPE_CHOICES = [
        ('SEAT', 'Seat Request'),
        ('TRANSFER', 'Transfer Request'),
    ]

    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    ]

    student = models.ForeignKey(Usermodel, on_delete=models.CASCADE, null=True,blank=True)
    college = models.ForeignKey(collegemodel, on_delete=models.CASCADE)
    program = models.ForeignKey(vacancy, on_delete=models.CASCADE)
    request_type = models.CharField(max_length=10, choices=REQUEST_TYPE_CHOICES)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='PENDING')
    date_submitted = models.DateTimeField(default=datetime.now)
    reason = models.TextField(blank=True, null=True)



class College(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    description = models.TextField()


class review(models.Model):
    user = models.ForeignKey(Usermodel, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(default=0)
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"Feedback from {self.user.username}"

class Complaint(models.Model):
    sender = models.ForeignKey(Usermodel, on_delete=models.CASCADE, blank=True, null=True)
    complaint_text = models.TextField(max_length=1000, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    reply = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=[
            ('pending', 'Pending'),
            ('resolved', 'Resolved'),
            ('under_review', 'Under Review'),
            ('closed', 'Closed'),
        ], default='pending')

    def _str_(self):
        return f"{self.sender.username}"

college/forms.py
from django import forms
from .models import *

class collegeform(forms.ModelForm):
    class Meta:
        model=collegemodel
        fields ='__all__'


class NotificationForm(forms.ModelForm):
    class Meta:
        model = ExamNotification
        fields = ['subject', 'notification_content', 'exam_date']


class addmission_form(forms.ModelForm):
    class Meta:
        model = Addmission_details
        fields = '__all__'

class document_form(forms.ModelForm):
    class Meta:
        model = addmission_documents
        fields = '__all__'

class facility_form(forms.ModelForm):
    class Meta:
        model=Facility
        fields = '__all__'

class programme_form(forms.ModelForm):
    class Meta:
        model=programm_notification
        fields = '__all__'

class vacancy_form(forms.ModelForm):
    class Meta:
        model =vacancy
        fields = '__all__'

class about_form(forms.ModelForm):
    class Meta:
        model = about
        fields = '__all__'
        

student/forms.py
from django import forms
from .models import *

class studentform(forms.ModelForm):
    class Meta:
        model = studentmodel
        fields = [
            'Name', 'Age', 'Date_of_birth', 'Email', 'Father_name', 'Mother_name',
            'Gender', 'City', 'Ph_num', 'Addar_num', 'Qualification'
        ]


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'


class SeatTransferRequestForm(forms.ModelForm):
    class Meta:
        model = SeatTransferRequest
        fields = ['college', 'program', 'request_type', 'reason']


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['complaint_text']
        widgets = {
            'complaint_text': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
        }

templates/college/addmission_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admission Details</title>
    <style>
        body {
            font-family: 'Tahoma', sans-serif;
            background-color: #eaf0f9;
            color: #4a4a4a;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        h1 {
            text-align: center;
            color: #003366;
        }

        form {
            background: #ffffff;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 6px 10px rgba(0, 0, 0, 0.2);
            width: 100%;
            max-width: 650px;
        }

        table {
            width: 100%;
            margin-bottom: 25px;
        }

        th {
            font-weight: bold;
            text-align: left;
            padding-bottom: 12px;
        }

        input[type="text"], input[type="date"] {
            width: 100%;
            padding: 12px;
            border: 1px solid #003366;
            border-radius: 6px;
            background-color: #f5f9fd;
            font-size: 16px;
        }

        input[type="submit"] {
            background-color: #003366;
            color: white;
            padding: 15px 35px;
            border: none;
            border-radius: 6px;
            font-size: 18px;
            cursor: pointer;
            width: 100%;
            margin-top: 20px;
        }

        input[type="submit"]:hover {
            background-color: #002244;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h1>Admission Details</h1>
        <table>
            <tr>
                <th><label for="id_college_name">College Name</label></th>
                <td><input type="text" id="id_college_name" name="college_name"></td>
            </tr>
            <tr>
                <th><label for="id_Eligibility">Eligibility</label></th>
                <td><input type="text" id="id_Eligibility" name="Eligibility"></td>
            </tr>
            <tr>
                <th><label for="id_Subject">Subject</label></th>
                <td><input type="text" id="id_Subject" name="Subject"></td>
            </tr>
            <tr>
                <th><label for="id_Addmission_start_date">Admission Start Date</label></th>
                <td><input type="date" id="id_Addmission_start_date" name="Addmission_start_date"></td>
            </tr>
            <tr>
                <th><label for="id_Addmission_end_date">Admission End Date</label></th>
                <td><input type="date" id="id_Addmission_end_date" name="Addmission_end_date"></td>
            </tr>
        </table>
        <div>
            <input type="submit" value="Submit">
        </div>
    </form>
</body>
</html>

templates/college/addmission_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>College Details</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: linear-gradient(135deg, #4caf50, #81c784);
            color: #333;
        }

        .form-container {
            width: 100%;
            max-width: 600px;
            background: #ffffff;
            padding: 30px 40px;
            border-radius: 15px;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
            box-sizing: border-box;
        }

        h2 {
            text-align: center;
            font-size: 28px;
            color: #2c3e50;
            margin-bottom: 20px;
        }

        label {
            display: block;
            font-weight: 600;
            margin-bottom: 5px;
            color: #444;
        }

        input[type="text"], input[type="date"], input[type="file"] {
            width: 100%;
            padding: 10px 12px;
            margin-bottom: 15px;
            border: 1px solid #ddd;
            border-radius: 8px;
            font-size: 16px;
            box-sizing: border-box;
        }

        input[type="text"]:focus, input[type="date"]:focus, input[type="file"]:focus {
            border-color: #4CAF50;
            box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);
            outline: none;
        }

        button[type="submit"] {
            width: 100%;
            padding: 12px;
            font-size: 18px;
            font-weight: bold;
            color: white;
            background-color: #4caf50;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: all 0.3s ease;
        }

        button[type="submit"]:hover {
            background-color: #388e3c;
        }

        @media (max-width: 600px) {
            .form-container {
                padding: 20px;
            }

            h2 {
                font-size: 22px;
            }
        }
    </style>
</head>
<body>

<div class="form-container">
    <h2>Edit College Details</h2>
    <form method="POST" class="edit">
        {% csrf_token %}
        <label for="id_college_name">College Name</label>
        <input type="text" id="id_college_name" name="college_name" value="{{ edited.college_name }}">

        <label for="id_Eligibility">Eligibility</label>
        <input type="text" id="id_Eligibility" name="Eligibility" value="{{ edited.Eligibility }}">

        <label for="id_Subject">Subject</label>
        <input type="text" id="id_Subject" name="Subject" value="{{ edited.Subject }}">

        <label for="id_Addmission_start_date">Admission Start Date</label>
        <input type="date" id="id_Addmission_start_date" name="Addmission_start_date" value="{{ edited.Addmission_start_date|date:'Y-m-d' }}">

        <label for="id_Addmission_end_date">Admission End Date</label>
        <input type="date" id="id_Addmission_end_date" name="Addmission_end_date" value="{{ edited.Addmission_end_date|date:'Y-m-d' }}">

        <button type="submit">Save</button>
    </form>
</div>

</body>
</html>

templates/college/document_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Management</title>
    <style>
        /* Global Styles */
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f9fafb;
            margin: 0;
            padding: 0;
            color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 90%;
            max-width: 1000px;
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            overflow-y: auto;
        }

        h1 {
            font-size: 28px;
            font-weight: 600;
            text-align: center;
            margin-bottom: 30px;
            color: #4caf50;
        }

        .document-card {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.05);
            transition: box-shadow 0.3s ease;
        }

        .document-card:hover {
            box-shadow: 0 6px 14px rgba(0, 0, 0, 0.1);
        }

        .document-card .doc-info {
            flex-grow: 1;
            padding-right: 20px;
        }

        .document-card h3 {
            font-size: 20px;
            color: #333;
            margin-bottom: 8px;
        }

        .document-card p {
            color: #777;
            font-size: 14px;
        }

        .document-card a {
            color: #4caf50;
            text-decoration: none;
            font-size: 14px;
            margin-top: 10px;
            display: inline-block;
            transition: color 0.3s ease;
        }

        .document-card a:hover {
            color: #388e3c;
        }

        .document-card input[type="file"] {
            padding: 12px;
            border-radius: 6px;
            border: 2px solid #ddd;
            font-size: 14px;
            background-color: #fff;
            width: 100%;
            cursor: pointer;
            transition: border-color 0.3s ease;
        }

        .document-card input[type="file"]:hover {
            border-color: #4caf50;
        }

        /* Form Actions */
        .form-actions {
            display: flex;
            justify-content: center;
            margin-top: 40px;
        }

        .form-actions button {
            background-color: #4caf50;
            color: white;
            font-size: 16px;
            padding: 12px 25px;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .form-actions button:hover {
            background-color: #388e3c;
        }

        .form-actions button:active {
            transform: translateY(2px);
        }

        /* Hover Effects */
        .document-card input[type="file"]:focus {
            outline: none;
            border-color: #388e3c;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }

            .document-card {
                flex-direction: column;
                text-align: center;
            }

            .document-card .doc-info {
                padding-right: 0;
                margin-bottom: 15px;
            }

            .form-actions button {
                width: 100%;
                padding: 15px 20px;
                font-size: 18px;
            }

            .document-card input[type="file"] {
                width: 100%;
            }
        }

        /* Scrollable Content */
        .container {
            max-height: 90vh;
            overflow-y: auto;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Manage Your Documents</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="document-card">
                <div class="doc-info">
                    <h3>SSLC Certificate</h3>
                    {% if data.Sslc_certificate %}
                        <object data="{{ data.Sslc_certificate.url }}" type="application/pdf" width="300" height="400"></object><br>
                        <a href="{{ data.Sslc_certificate.url }}" target="_blank">View Certificate</a>
                    {% endif %}
                </div>
                <input type="file" id="id_Sslc_certificate" name="Sslc_certificate" />
            </div>

            <div class="document-card">
                <div class="doc-info">
                    <h3>Plus Two Certificate</h3>
                    {% if data.Plustwo_certificate %}
                        <object data="{{ data.Plustwo_certificate.url }}" type="application/pdf" width="300" height="400"></object><br>
                        <a href="{{ data.Plustwo_certificate.url }}" target="_blank">View Certificate</a>
                    {% endif %}
                </div>
                <input type="file" id="id_Plustwo_certificate" name="Plustwo_certificate" />
            </div>

            <div class="document-card">
                <div class="doc-info">
                    <h3>ID Card</h3>
                    {% if data.ID_card %}
                        <object data="{{ data.ID_card.url }}" type="application/pdf" width="300" height="400"></object><br>
                        <a href="{{ data.ID_card.url }}" target="_blank">View Certificate</a>
                    {% endif %}
                </div>
                <input type="file" id="id_ID_card" name="ID_card" />
            </div>

            <div class="document-card">
                <div class="doc-info">
                    <h3>Transfer Certificate</h3>
                    {% if data.TC %}
                        <object data="{{ data.TC.url }}" type="application/pdf" width="300" height="400"></object><br>
                        <a href="{{ data.TC.url }}" target="_blank">View Certificate</a>
                    {% endif %}
                </div>
                <input type="file" id="id_TC" name="TC" />
            </div>

            <div class="document-card">
                <div class="doc-info">
                    <h3>Course Certificate</h3>
                    {% if data.CC %}
                        <object data="{{ data.CC.url }}" type="application/pdf" width="300" height="400"></object><br>
                        <a href="{{ data.CC.url }}" target="_blank">View Certificate</a>
                    {% endif %}
                </div>
                <input type="file" id="id_CC" name="CC" />
            </div>

            <div class="form-actions">
                <button type="submit">Save Changes</button>
            </div>
        </form>
    </div>

</body>
</html>

templates/college/programme_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table border="1px">
    <form class="edit" method="POST">
        {% csrf_token %}

        <tr>
            <th><label for="id_Titel">Titel</label></th>
             <td><input type="text" id="id_Titel" name="Titel" value="{{ programme.Titel}}"></td>
    </tr>
        <tr>
            <th><lable for="id_Venue">Venue</lable></th>
            <td><input type="text" id="id_Venue" name="Venue" value="{{ programme.Venue }}"></td>
        </tr>
        <tr>
            <th><label for="id_Start_date">Start_date</label> </th>
        <td>
                <input type="datetime-local" id="id_Start_date" name="Start_date" value="{{ programme.Start_date|date:'Y-m-d\\TH:i' }}">
            </td>
        </tr>
        <tr>
            <th><lable for="id_End_date">End_date</lable></th>
       <td><input type="datetime-local" id="id_End_date" name="End_date" value="{{ programme.End_date|date:'Y-m-d\\TH:i' }}">
        </tr>
        <tr>
            <td><button type="submit">save</button></td>
        </tr>
    </form>
</table>
</body>
</html>